### ISSUE TITLE
explore linode server to see if it can used for deployment

### ISSUE THREAD

**Issue by thethanghn** [GoldenOwlAsia/operations#8]

**Comment by Rosedao03** [comment]
next monday

**Comment by lhhieu89** [comment]
Vì Linode tính phí nên chúng ta sẽ tiếp tục dùng Heroku hoặc Openshift để làm staging, gói nhỏ nhất của Linode là 10$.
Cơ bản nếu cùng mức giá thì nó giống Digital Ocean.
Digital Ocean buộc mình chọn hệ điều hành có sẵn, còn trên Linode mình có thể cài đặt hệ điều hành mình muốn.
Linode chỉ chấp nhận thanh toán bằng Visa nên không được thông dụng với giới sinh viên và freelancer.
Mặc dù có một số trang benchmark sẵn nhưng tốc độ đường truyền và sự ổn định còn phụ thuộc vào location đặt server nữa nên phải dùng thử mới biết được.
